#!/usr/bin/env python3
import sys
from GithubCheck import check

github = {
    'author': "supertuxkart",
    'project': "stk-code",
    "suffix": "linux-64bit.tar.xz",
    "prefix": ""
}

if __name__ == "__main__":
    sys.exit(check(github, "X86"))
