#!/usr/bin/env python3
from SourceforgeCheck import check

sourceforge = {
    "project": "sweethome3d",
    "d_filename": "SweetHome3D-(.*)-linux-x64.tgz",
    "arch": "X86"
}

if __name__ == "__main__":
    SystemExit(check(sourceforge))
