#!/usr/bin/env python3
import sys
from GithubCheck import check

github = {
    'author': "OpenShot",
    'project': "openshot-qt",
    "suffix": "AppImage",
    "prefix": ""
}

if __name__ == "__main__":
    sys.exit(check(github, "X86"))
