#!/usr/bin/env python3
import sys
from GithubCheck import check

github = {
    'author': "ahrm",
    'project': "sioyek",
    "suffix": "linux-gcc8.zip",
    "prefix": ""
}

if __name__ == "__main__":
    sys.exit(check(github, "X86"))
