#!/bin/env python3
import sys
from GithubCheck import check

github = {
    'author': "bitwarden",
    'project': "desktop",
    "suffix": "AppImage",
    "prefix": ""
}

if __name__ == "__main__":
    sys.exit(check(github, "X86"))
