#!/usr/bin/env python3
import sys
from GithubCheck import check

github = {
    'author': "veyon",
    'project': "veyon",
    "suffix": "debian-buster_amd64.deb",
    "prefix": ""
}

if __name__ == "__main__":
    sys.exit(check(github, "X86"))
