#!/bin/env python3
import sys
from GithubCheck import check

github = {
    'author': "Fndroid",
    'project': "clash_for_windows_pkg",
    "suffix": "x64-linux.tar.gz",
    "prefix": ""
}

if __name__ == "__main__":
    sys.exit(check(github, "X86"))
