#!/bin/env python3
from pyvirtualdisplay import Display
disp = Display(use_xauth=True)
disp.start()

from sys import argv
from os import environ
from AppstoreCheck import Appstore
from Utils import get_conf
from requests import post

appid = argv[1]
version = argv[2]
packagedFile = argv[3]
feedback_url = environ['COOPERATION_URL']

appstore = Appstore(environ['APPUSERNAME'], environ['APPPASSWORD'])
conf = get_conf("apps/" + appid + "/info.yml")
appstore.uploadUpdate(appid=conf.get("id"), file=packagedFile)
if (appstore.getVersion(appid=conf.get("id")).__eq__(version)):
    data = appstore.__search(appid=conf.get("id"))
    res = post(url = feedback_url, json={
            "package": appid,
            "detail": data['app_name'],
            "version": version,
            "systemStr": appstore.get_all_systemStr(conf.get("id")),
            "appid": conf.get("id")
        })
disp.stop()
