#!/usr/bin/env python3
from pyvirtualdisplay import Display
disp = Display(use_xauth=True, visible=False, size=(1920, 1080))
disp.start()

from sys import argv
from os import environ
from AppstoreCheck import Appstore
from Utils import get_conf
from requests import post

appid = argv[1]
version = argv[2]
arch = argv[3]
packagedFile = argv[4]
feedback_url = environ['COOPERATION_URL']

appstore = Appstore(environ['APPUSERNAME'], environ['APPPASSWORD'])
conf = get_conf("apps/" + appid + "/info.yml")
appstore.uploadUpdate(appid=conf.get("id"), arch=arch, file=packagedFile)
_, _, ver = appstore.getVersion(appid=conf.get("id"))
if ver.__eq__(version):
    data = appstore.search(appid=conf.get("id"))
    res = post(url = feedback_url, json={
            "package": appid,
            "detail": data['app_name'],
            "version": version,
            "systemStr": appstore.get_all_systemStr(conf.get("id")),
            "appid": conf.get("id")
        })
disp.stop()
