#!/bin/env python3
import sys
from GithubCheck import check

github = {
    'author': "popcorn-official",
    'project': "popcorn-desktop",
    "suffix": "linux64.zip",
    "prefix": "Popcorn-Time"
}

if __name__ == "__main__":
    sys.exit(check(github, "X86"))
