#!/usr/bin/env python3
from sys import exit,argv
from GithubAction import setOutput
from Utils import Downloader

def main():
    setOutput("FILE", Downloader().run(argv[1]))

if __name__ == "__main__":
    exit(main())
